//! Reports: one line per metric, in Markdown for people and JSON for machines.

use serde::{Deserialize, Serialize};

use crate::case::Tolerance;

/// How one metric came out.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
#[non_exhaustive]
pub enum Verdict {
    /// Inside its tolerance.
    Pass,
    /// Outside it.
    Fail,
}

/// One metric of one case: what the oracle said, what hpr said, and whether that is close enough.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Comparison {
    /// The case's id.
    pub case: String,
    /// The metric's name.
    pub metric: String,
    /// What hpr measured.
    pub measured: f64,
    /// What the reference says.
    pub reference: f64,
    /// Where the reference value came from.
    pub source: String,
    /// The tolerance it was held to.
    pub tolerance: Tolerance,
    /// `measured − reference`.
    pub difference: f64,
    /// That difference as a fraction of the reference, where the reference is not zero.
    pub relative: Option<f64>,
    /// Pass or fail.
    pub verdict: Verdict,
}

impl Comparison {
    /// Compares `measured` against `reference` under `tolerance`.
    #[must_use]
    pub fn new(
        case: &str,
        metric: &str,
        measured: f64,
        reference: f64,
        source: &str,
        tolerance: Tolerance,
    ) -> Self {
        let difference = measured - reference;
        Self {
            case: case.to_owned(),
            metric: metric.to_owned(),
            measured,
            reference,
            source: source.to_owned(),
            tolerance,
            difference,
            relative: (reference != 0.0).then(|| difference / reference),
            verdict: if tolerance.accepts(measured, reference) {
                Verdict::Pass
            } else {
                Verdict::Fail
            },
        }
    }
}

/// Where a case's reference came from.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Source {
    /// The case's id.
    pub case: String,
    /// The oracle, as its generator records it.
    pub oracle: String,
    /// The generator script.
    pub generator: String,
    /// The command that regenerates the reference.
    pub command: String,
}

/// A whole run: every comparison, and what it adds up to.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Report {
    /// The hpr version that produced it.
    pub hpr_version: String,
    /// Whether the run was `--fast`.
    pub fast: bool,
    /// The cases it covered, in lock order.
    pub cases: Vec<String>,
    /// Every metric compared.
    pub comparisons: Vec<Comparison>,
    /// Where each case's reference came from, in case order.
    pub sources: Vec<Source>,
}

impl Report {
    /// Whether every comparison passed.
    #[must_use]
    pub fn passed(&self) -> bool {
        self.comparisons
            .iter()
            .all(|comparison| comparison.verdict == Verdict::Pass)
    }

    /// The comparisons that failed.
    #[must_use]
    pub fn failures(&self) -> Vec<&Comparison> {
        self.comparisons
            .iter()
            .filter(|comparison| comparison.verdict == Verdict::Fail)
            .collect()
    }

    /// The report as Markdown: a summary line, then one table row per metric.
    ///
    /// It carries no date, so a run that changes nothing changes no bytes and the committed report
    /// only moves when a number does.
    #[must_use]
    pub fn to_markdown(&self) -> String {
        let mut out = String::new();
        out.push_str("# Validation report\n\n");
        out.push_str(&format!(
            "hpr {}, {} case(s), {} metric(s), {}{}.\n\n",
            self.hpr_version,
            self.cases.len(),
            self.comparisons.len(),
            if self.passed() {
                "all within tolerance"
            } else {
                "OUT OF TOLERANCE: "
            },
            if self.passed() {
                String::new()
            } else {
                format!("{} metric(s) failed", self.failures().len())
            }
        ));
        if self.fast {
            out.push_str("Run with `--fast`, so the slow cases were left out.\n\n");
        }
        out.push_str(
            "Generated by `cargo xtask validate`. Every reference value names its own \
                      source; the generators are under `validation/oracles/`.\n\n",
        );
        out.push_str("| case | metric | hpr | reference | difference | tolerance | verdict |\n");
        out.push_str("|---|---|---|---|---|---|---|\n");
        for comparison in &self.comparisons {
            let relative = comparison.relative.map_or_else(
                || format!("{:+.6}", comparison.difference),
                |relative| format!("{:+.3}%", 100.0 * relative),
            );
            out.push_str(&format!(
                "| {} | {} | {:.6} | {:.6} | {} | {} | {} |\n",
                comparison.case,
                comparison.metric,
                comparison.measured,
                comparison.reference,
                relative,
                comparison.tolerance.describe(),
                match comparison.verdict {
                    Verdict::Pass => "pass",
                    Verdict::Fail => "**fail**",
                }
            ));
        }
        out.push_str("\n## References\n\n");
        out.push_str("| case | oracle | generator | regenerate with |\n|---|---|---|---|\n");
        for source in &self.sources {
            out.push_str(&format!(
                "| {} | {} | `{}` | `{}` |\n",
                source.case, source.oracle, source.generator, source.command
            ));
        }
        out.push_str(
            "\nA reference moves only when its generator runs, which is a deliberate step: it is \
             never regenerated to make a comparison pass (Loft lesson L76).\n",
        );
        out
    }
}
