//! `cargo xtask designs [--check]`: writes the public test designs in `validation/designs/`.
//!
//! - `rocketpy-<case>.json`: RocketPy's example rockets, built from the RocketPy oracle fixture
//!   `validation/fixtures/design/rocketpy-rocket-mass.json` (generated by
//!   `validation/oracles/rocketpy/rocket_mass.py`). Each stage override is the example's mass,
//!   centre and inertia without the motor. Each motor is the example's, with the bundled
//!   public-domain curve the fixture substitutes. The geometry (nose, body tubes, tails, fins,
//!   rail buttons) follows the example, for the aerodynamics milestones.
//! - `synthetic-*.json`: rockets whose mass comes from their geometry.
//!
//! `--check` compares instead of writing, and a test runs it, so the committed files always match
//! this generator. It fails on a missing or extra `.json` file and on any difference in content.
//! Numbers compare to 1e-12 relative, because a platform's `tan` (for swept fins) may round its
//! last bit differently; formatting is not compared.

use std::fs;
use std::path::{Path, PathBuf};

use hpr_design::materials;
use hpr_design::{
    AutoDimension, BodyTube, CenteringRing, Component, Configuration, FinCrossSection, FinPlanform,
    FinSet, Finish, InertiaOverride, InnerTube, MassComponent, Material, MotorMount, MountedMotor,
    NoseCone, NoseShape, Overrides, Packing, Parachute, Part, Position, RailButton,
    ReferenceDiameter, Rocket, ShockCord, Shoulder, Stage, Transition, Wall,
};
use hpr_motor::motor::STANDARD_SEA_LEVEL_PRESSURE_PA;
use hpr_motor::{
    BatesGrains, Catalog, Delay, MassElement, Nozzle, Propellant, PropellantColumn, SolidMotor,
    catalog::bundled_curve_text,
};
use serde_json::Value;

pub const USAGE: &str = "\
  designs [--check]        Write validation/designs/ (RocketPy's example rockets from the
                           oracle fixture, and the synthetic rockets). --check fails if a
                           committed file differs instead of writing.";

const FIXTURE: &str = "validation/fixtures/design/rocketpy-rocket-mass.json";
const DIR: &str = "validation/designs";

pub fn run(args: &[String]) -> Result<(), String> {
    let check = match args {
        [] => false,
        [flag] if flag == "--check" => true,
        _ => return Err(format!("usage:\n{USAGE}")),
    };
    let root = root()?;
    let designs = generate(&root)?;
    let dir = root.join(DIR);
    if check {
        let stale = stale(&dir, &designs);
        if stale.is_empty() {
            println!("{} designs match the generator", designs.len());
            return Ok(());
        }
        return Err(format!(
            "these designs differ from `cargo xtask designs`: {}",
            stale.join(", ")
        ));
    }
    let unknown = extra(&dir, &designs);
    if !unknown.is_empty() {
        return Err(format!(
            "{DIR} holds files the generator doesn't write; remove them or add them to it: {}",
            unknown.join(", ")
        ));
    }
    fs::create_dir_all(&dir).map_err(|e| format!("{}: {e}", dir.display()))?;
    for (name, text) in &designs {
        let path = dir.join(name);
        fs::write(&path, text).map_err(|e| format!("{}: {e}", path.display()))?;
        println!("wrote {DIR}/{name}");
    }
    Ok(())
}

pub fn root() -> Result<PathBuf, String> {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .map(Path::to_path_buf)
        .ok_or_else(|| "xtask has no parent directory".to_owned())
}

/// The `.json` files in `dir` that the generator doesn't write.
fn extra(dir: &Path, designs: &[(String, String)]) -> Vec<String> {
    let Ok(entries) = fs::read_dir(dir) else {
        return Vec::new();
    };
    let mut names: Vec<String> = entries
        .filter_map(|e| e.ok()?.file_name().into_string().ok())
        .filter(|name| name.ends_with(".json") && !designs.iter().any(|(n, _)| n == name))
        .collect();
    names.sort();
    names
}

/// The files in `dir` that differ from `designs`: missing, extra, unreadable, or with different
/// content.
fn stale(dir: &Path, designs: &[(String, String)]) -> Vec<String> {
    let mut stale: Vec<String> = designs
        .iter()
        .filter(|(name, text)| {
            let committed = fs::read_to_string(dir.join(name)).ok();
            let parse = |t: &str| serde_json::from_str::<Value>(t).ok();
            match (committed.as_deref().and_then(parse), parse(text)) {
                (Some(a), Some(b)) => !same(&a, &b),
                _ => true,
            }
        })
        .map(|(name, _)| name.clone())
        .collect();
    stale.extend(extra(dir, designs));
    stale
}

/// Whether two JSON values are equal, with numbers equal to 1e-12 relative.
pub fn same(a: &Value, b: &Value) -> bool {
    match (a, b) {
        (Value::Number(x), Value::Number(y)) => match (x.as_f64(), y.as_f64()) {
            (Some(x), Some(y)) => x == y || (x - y).abs() <= 1e-12 * x.abs().max(y.abs()),
            _ => x == y,
        },
        (Value::Array(x), Value::Array(y)) => {
            x.len() == y.len() && x.iter().zip(y).all(|(x, y)| same(x, y))
        }
        (Value::Object(x), Value::Object(y)) => {
            x.len() == y.len() && x.iter().all(|(k, v)| y.get(k).is_some_and(|w| same(v, w)))
        }
        _ => a == b,
    }
}

/// Every design as `(file name, pretty JSON)`.
pub fn generate(root: &Path) -> Result<Vec<(String, String)>, String> {
    let path = root.join(FIXTURE);
    let fixture: Value = serde_json::from_str(
        &fs::read_to_string(&path).map_err(|e| format!("{}: {e}", path.display()))?,
    )
    .map_err(|e| format!("{FIXTURE}: {e}"))?;
    let catalog = Catalog::bundled().map_err(|e| e.to_string())?;
    let mut designs = Vec::new();
    let cases = fixture["cases"]
        .as_array()
        .ok_or_else(|| format!("{FIXTURE} has no cases"))?;
    for case in cases {
        let name = text(case, "name")?;
        let rocket = rocketpy_design(case, &catalog).map_err(|e| format!("{name}: {e}"))?;
        designs.push((format!("rocketpy-{name}.json"), to_json(&rocket)?));
    }
    designs.push((
        "synthetic-54mm-three-fin.json".to_owned(),
        to_json(&three_fin(&catalog)?)?,
    ));
    designs.push((
        "synthetic-two-stage-75mm-54mm.json".to_owned(),
        to_json(&two_stage(&catalog)?)?,
    ));
    Ok(designs)
}

fn to_json(rocket: &Rocket) -> Result<String, String> {
    serde_json::to_string_pretty(rocket)
        .map(|mut s| {
            s.push('\n');
            s
        })
        .map_err(|e| e.to_string())
}

fn num(v: &Value, key: &str) -> Result<f64, String> {
    v[key]
        .as_f64()
        .ok_or_else(|| format!("`{key}` is missing or not a number"))
}

fn text<'a>(v: &'a Value, key: &str) -> Result<&'a str, String> {
    v[key]
        .as_str()
        .ok_or_else(|| format!("`{key}` is missing or not a string"))
}

fn material(id: &str) -> Result<Material, String> {
    materials::find(id)
        .map(materials::BuiltinMaterial::material)
        .ok_or_else(|| format!("no built-in material `{id}`"))
}

fn component(id: &str, part: Part, position: Option<Position>) -> Component {
    Component {
        id: id.to_owned(),
        name: String::new(),
        part,
        position,
        auto: Vec::new(),
        motor_mount: None,
        finish: None,
        overrides: Overrides::default(),
        overrides_include_children: false,
        children: Vec::new(),
    }
}

/// Where a bundled curve file is listed, with its motor.
fn bundled_curve<'a>(
    catalog: &'a Catalog,
    file: &str,
) -> Result<(&'a hpr_motor::CatalogMotor, &'a hpr_motor::CatalogCurve), String> {
    catalog
        .motors
        .iter()
        .find_map(|m| m.curves.iter().find(|c| c.file == file).map(|c| (m, c)))
        .ok_or_else(|| format!("no bundled curve `{file}`"))
}

/// Wall thicknesses and fin thickness for the RocketPy examples, m. The examples give no
/// structure (their masses are inputs), so these only make the parts real; the stage override
/// replaces their mass. The fin thickness is also a drag input: a NACA 00xx airfoil in the
/// example sets it instead.
const WALL_M: f64 = 0.002;
const FIN_THICKNESS_M: f64 = 0.003;
/// The examples whose drag curves RocketPy labels RASAero. RASAero II's exports don't record
/// their inputs, so these designs take its documented default surface finish, smooth (RASAero II
/// Users Manual, 2019, p. 53), for the drag comparison (ADR-009).
const RASAERO_CURVES: &[&str] = &[
    "calisto-getting-started-motor-at-minus-1.255",
    "calisto-tests-motor-at-minus-1.373",
    "juno-iii",
    "valetudo",
    "cavour",
];
const MOUNT_WALL_M: f64 = 0.0015;
/// Below this, a gap between the example's last tail and its nozzle or fins gets no closing tube.
const CLOSING_TUBE_MIN_M: f64 = 0.01;
const MATCH_M: f64 = 1e-9;

/// A RocketPy example rocket from its oracle-fixture case.
fn rocketpy_design(case: &Value, catalog: &Catalog) -> Result<Rocket, String> {
    let rocket = &case["rocket"];
    let motor = &case["motor"];
    let geometry = &case["geometry"];
    let scalars = &case["scalars"];
    let glass = material("fiberglass_g10")?;

    // Stations run aft from the nose tip.
    let nose = &geometry["nose"];
    let tip = num(nose, "position")?;
    let sign = match text(rocket, "coordinate_system_orientation")? {
        "tail_to_nose" => -1.0,
        "nose_to_tail" => 1.0,
        other => return Err(format!("unknown rocket orientation `{other}`")),
    };
    let station = |z: f64| sign * (z - tip);

    let radius = num(rocket, "radius")?;
    let nose_length = num(nose, "length")?;
    let base_radius = nose["base_radius"].as_f64().unwrap_or(radius);
    let shape = match text(nose, "kind")?.to_lowercase().replace(' ', "").as_str() {
        "vonkarman" => NoseShape::Haack { parameter: 0.0 },
        "tangent" => NoseShape::Ogive { radius_ratio: 1.0 },
        "elliptical" => NoseShape::Elliptical {},
        other => return Err(format!("unmapped nose kind `{other}`")),
    };
    let mut body = vec![component(
        "nose",
        Part::NoseCone(NoseCone {
            shape,
            length_m: nose_length,
            base_radius_m: base_radius,
            wall: Wall::Shell {
                thickness_m: WALL_M,
            },
            shoulder: None,
            material: glass.clone(),
        }),
        None,
    )];

    // Tails, forward to aft, with body tubes between them.
    let mut tails = Vec::new();
    for tail in geometry["tails"].as_array().into_iter().flatten() {
        tails.push((
            station(num(tail, "position")?),
            num(tail, "top_radius")?,
            num(tail, "bottom_radius")?,
            num(tail, "length")?,
        ));
    }
    tails.sort_by(|a, b| a.0.total_cmp(&b.0));
    let nozzle_station = station(num(scalars, "nozzle_position_m")?);
    let fin_sets: Vec<&Value> = geometry["fin_sets"]
        .as_array()
        .into_iter()
        .flatten()
        .collect();
    let mut aft_end = nozzle_station;
    for fins in &fin_sets {
        aft_end = aft_end.max(station(num(fins, "position")?) + num(fins, "root_chord")?);
    }
    let tube = |id: String, length_m: f64, outer_radius_m: f64| {
        component(
            &id,
            Part::BodyTube(BodyTube {
                length_m,
                outer_radius_m,
                thickness_m: WALL_M,
                material: glass.clone(),
            }),
            None,
        )
    };
    let (mut s, mut r) = (nose_length, base_radius);
    let mut tubes = 0;
    for (k, &(fore, top, bottom, length)) in tails.iter().enumerate() {
        if fore < s - MATCH_M || (top - r).abs() > MATCH_M {
            return Err(format!("tail {k} doesn't follow the body at station {s} m"));
        }
        if fore > s + MATCH_M {
            tubes += 1;
            body.push(tube(format!("body-tube-{tubes}"), fore - s, r));
        }
        body.push(component(
            &format!("tail-{}", k + 1),
            Part::Transition(Transition {
                shape: NoseShape::Conical {},
                clipped: false,
                length_m: length,
                fore_radius_m: top,
                aft_radius_m: bottom,
                wall: Wall::Shell {
                    thickness_m: WALL_M,
                },
                fore_shoulder: None,
                aft_shoulder: None,
                material: glass.clone(),
            }),
            None,
        ));
        (s, r) = (fore + length, bottom);
    }
    if tails.is_empty() || aft_end > s + CLOSING_TUBE_MIN_M {
        tubes += 1;
        body.push(tube(format!("body-tube-{tubes}"), aft_end - s, r));
    }

    // Stations of each body component, to attach parts to the tube they sit on.
    let mut spans = Vec::new();
    let mut fore = 0.0;
    for c in &body {
        let length = c.part.length_m();
        spans.push((fore, fore + length));
        fore += length;
    }
    let tube_at = |s: f64| {
        body.iter()
            .zip(&spans)
            .position(|(c, &(f, a))| matches!(c.part, Part::BodyTube(_)) && f <= s && s < a)
            .ok_or_else(|| format!("no body tube at station {s} m"))
    };

    let mut attached: Vec<(usize, Component)> = Vec::new();
    for (k, fins) in fin_sets.iter().enumerate() {
        if text(fins, "type")? != "trapezoidal" {
            return Err("only trapezoidal fins are mapped".to_owned());
        }
        let leading = station(num(fins, "position")?);
        let index = tube_at(leading)?;
        let Part::BodyTube(on) = &body[index].part else {
            return Err("fins off a tube".to_owned());
        };
        if let Some(given) = fins["radius"].as_f64()
            && (given - on.outer_radius_m).abs() > MATCH_M
        {
            return Err(format!("fin radius {given} m is not its tube's"));
        }
        let (root, tip_chord, span) = (
            num(fins, "root_chord")?,
            num(fins, "tip_chord")?,
            num(fins, "span")?,
        );
        // RocketPy's default sweep puts the tip's trailing edge over the root's.
        let sweep = match (fins["sweep_length"].as_f64(), fins["sweep_angle"].as_f64()) {
            (Some(length), _) => length,
            (None, Some(degrees)) => degrees.to_radians().tan() * span,
            (None, None) => root - tip_chord,
        };
        let count = fins["n"]
            .as_u64()
            .and_then(|n| u32::try_from(n).ok())
            .ok_or("fin count")?;
        let planform = FinPlanform::Trapezoidal {
            root_chord_m: root,
            tip_chord_m: tip_chord,
            span_m: span,
            sweep_m: sweep,
        };
        let (cross_section, thickness) =
            fin_section(text(case, "name")?, &fins["airfoil"], &planform)?;
        attached.push((
            index,
            component(
                &format!("fins-{}", k + 1),
                Part::FinSet(FinSet {
                    count,
                    planform,
                    thickness_m: thickness,
                    cross_section,
                    tab: None,
                    cant_rad: fins["cant_angle"].as_f64().unwrap_or(0.0).to_radians(),
                    base_angle_rad: 0.0,
                    material: glass.clone(),
                }),
                Some(Position::Absolute { station_m: leading }),
            ),
        ));
    }

    let buttons = &geometry["rail_buttons"];
    if buttons.is_object() {
        let upper = station(num(buttons, "upper_button_position")?);
        let lower = station(num(buttons, "lower_button_position")?);
        let index = tube_at(upper)?;
        if tube_at(lower)? != index {
            return Err("the rail buttons sit on different tubes".to_owned());
        }
        // A 1010 button; RocketPy's default angle is 45°.
        let diameter = 0.0113;
        attached.push((
            index,
            component(
                "rail-buttons",
                Part::RailButton(RailButton {
                    outer_diameter_m: diameter,
                    inner_diameter_m: 0.0064,
                    height_m: 0.0081,
                    base_height_m: 0.002,
                    flange_height_m: 0.002,
                    angle_rad: buttons["angular_position"]
                        .as_f64()
                        .unwrap_or(45.0)
                        .to_radians(),
                    count: 2,
                    spacing_m: lower - upper,
                    material: material("acetal")?,
                }),
                Some(Position::Absolute {
                    station_m: upper - 0.5 * diameter,
                }),
            ),
        ));
    }

    // The motor, and a mount that fits it in the last tube starting forward of the nozzle.
    let solid = rocketpy_motor(motor, catalog)?;
    let (motor_radius, motor_length) = envelope(motor, &solid)?;
    let index = body
        .iter()
        .zip(&spans)
        .rposition(|(c, &(f, _))| matches!(c.part, Part::BodyTube(_)) && f < nozzle_station)
        .ok_or("no tube for the motor mount")?;
    let (tube_fore, tube_aft) = spans[index];
    let (offset, overhang) = if nozzle_station >= tube_aft {
        (0.0, nozzle_station - tube_aft)
    } else {
        (nozzle_station - tube_aft, 0.0)
    };
    if nozzle_station.min(tube_aft) - motor_length < tube_fore {
        return Err("the motor is longer than its tube".to_owned());
    }
    let mut mount = component(
        "motor-mount",
        Part::InnerTube(InnerTube {
            length_m: motor_length,
            outer_radius_m: motor_radius + MOUNT_WALL_M,
            thickness_m: MOUNT_WALL_M,
            radial_offset_m: 0.0,
            angle_rad: 0.0,
            material: glass.clone(),
        }),
        Some(Position::Bottom {
            aft_offset_m: offset,
        }),
    );
    mount.motor_mount = Some(MotorMount {
        overhang_m: overhang,
    });
    attached.insert(0, (index, mount));
    for (index, child) in attached {
        body[index].children.push(child);
    }
    let name = text(case, "name")?;
    if RASAERO_CURVES.contains(&name) {
        for part in &mut body {
            part.finish = Some(Finish::Mirror {});
            for child in &mut part.children {
                if child.part.is_external() {
                    child.finish = Some(Finish::Mirror {});
                }
            }
        }
    }

    let (entry, _) = bundled_curve(catalog, text(motor, "thrust_file")?)?;
    let original = text(case, "original_thrust_source")?;
    let inertia: Vec<f64> = rocket["inertia"]
        .as_array()
        .ok_or("rocket inertia")?
        .iter()
        .map(|v| v.as_f64().ok_or("rocket inertia"))
        .collect::<Result<_, _>>()?;
    let [i11, i22, i33] = inertia[..] else {
        return Err("only a three-value rocket inertia is mapped".to_owned());
    };
    if i11 != i22 {
        return Err("I_11 and I_22 differ".to_owned());
    }
    Ok(Rocket {
        name: format!("RocketPy example: {name}"),
        stages: vec![Stage {
            id: "rocket".to_owned(),
            name: String::new(),
            components: body,
            overrides: Overrides {
                mass_kg: Some(num(rocket, "mass")?),
                cg_aft_m: Some(station(num(rocket, "center_of_mass_without_motor")?)),
                // RocketPy's rocket has its centre on the axis; the rail buttons would move it.
                cg_xy_m: Some([0.0, 0.0]),
                inertia: Some(InertiaOverride::axisymmetric(i33, i11)),
            },
        }],
        reference_diameter: ReferenceDiameter::Maximum {},
        configurations: vec![Configuration {
            id: "example".to_owned(),
            name: format!(
                "the example's motor inputs with the {} curve in place of {original}",
                entry.designation
            ),
            motors: vec![MountedMotor {
                mount: "motor-mount".to_owned(),
                designation: entry.designation.clone(),
                diameter_m: 2.0 * motor_radius,
                length_m: motor_length,
                motor: solid,
                delay: None,
            }],
        }],
    })
}

/// Fin cross-sections published for an example's rocket outside RocketPy, by case name, with the
/// source. Juno III's team describes "aletas com perfil de aerofólio truncado" (fins with a
/// truncated airfoil profile, <https://www.projetojupiter.com/foguetes>): a rounded leading edge
/// and a blunt trailing edge, which Niskanen's rounded section (half the base drag) represents
/// better than the airfoil section (none).
const PUBLISHED_FIN_SECTIONS: &[(&str, FinCrossSection)] =
    &[("juno-iii", FinCrossSection::Rounded)];

/// A RocketPy fin set's cross-section and thickness (ADR-009): a NACA 00xx airfoil file gives an
/// airfoil section `xx`% thick at the mean aerodynamic chord; a section the rocket's team published
/// ([`PUBLISHED_FIN_SECTIONS`]) keeps the placeholder thickness; anything else, including a
/// lift-curve airfoil, which says nothing about the edges, keeps square edges of the placeholder
/// thickness.
fn fin_section(
    case: &str,
    airfoil: &Value,
    planform: &FinPlanform,
) -> Result<(FinCrossSection, f64), String> {
    if let Some(file) = airfoil["file"].as_str() {
        let digits = file
            .strip_prefix("NACA00")
            .and_then(|rest| rest.get(..2))
            .and_then(|d| d.parse::<u32>().ok())
            .ok_or_else(|| format!("unmapped airfoil file `{file}`"))?;
        let geometry =
            hpr_aero::fins::FinGeometry::from_planform(planform).map_err(|e| e.to_string())?;
        return Ok((
            FinCrossSection::Airfoil,
            f64::from(digits) / 100.0 * geometry.mac_length_m,
        ));
    }
    let section = PUBLISHED_FIN_SECTIONS
        .iter()
        .find(|(name, _)| *name == case)
        .map_or(FinCrossSection::Square, |&(_, section)| section);
    Ok((section, FIN_THICKNESS_M))
}

/// The fixture's RocketPy motor as an hpr `SolidMotor`: the same inputs on hpr's motor axis
/// (metres forward of the nozzle exit), with the bundled curve.
fn rocketpy_motor(motor: &Value, catalog: &Catalog) -> Result<SolidMotor, String> {
    let file = text(motor, "thrust_file")?;
    let (entry, curve) = bundled_curve(catalog, file)?;
    if curve.sha256 != text(motor, "thrust_file_sha256")? {
        return Err(format!("{file} is not the bundled bytes"));
    }
    let source = bundled_curve_text(&curve.file).ok_or("no bundled text")?;
    let thrust = entry
        .thrust_curve(curve, source)
        .map_err(|e| e.to_string())?;
    if !motor["burn_time"].is_null()
        || motor["reshape_thrust_curve"] != Value::Bool(false)
        || text(motor, "interpolation_method")? != "linear"
    {
        return Err("the fixture must use the whole curve, linearly".to_owned());
    }
    let sign = match text(motor, "coordinate_system_orientation")? {
        "nozzle_to_combustion_chamber" => 1.0,
        "combustion_chamber_to_nozzle" => -1.0,
        other => return Err(format!("unknown motor orientation `{other}`")),
    };
    let nozzle_position = num(motor, "nozzle_position")?;
    let to_hpr = |z: f64| sign * (z - nozzle_position);
    let dry_inertia: Vec<f64> = motor["dry_inertia"]
        .as_array()
        .ok_or("dry inertia")?
        .iter()
        .map(|v| v.as_f64().ok_or("dry inertia"))
        .collect::<Result<_, _>>()?;
    let [dry_11, dry_22, dry_33] = dry_inertia[..] else {
        return Err("only a three-value dry inertia is mapped".to_owned());
    };
    if dry_11 != dry_22 {
        return Err("dry I_11 and I_22 differ".to_owned());
    }
    let (propellant, dry_cg, throat) = match text(motor, "motor_kind")? {
        "solid" => (
            Propellant::Grains(BatesGrains {
                count: motor["grain_number"]
                    .as_u64()
                    .and_then(|n| u32::try_from(n).ok())
                    .ok_or("grain_number")?,
                density_kg_m3: num(motor, "grain_density")?,
                outer_radius_m: num(motor, "grain_outer_radius")?,
                initial_inner_radius_m: num(motor, "grain_initial_inner_radius")?,
                initial_height_m: num(motor, "grain_initial_height")?,
                separation_m: num(motor, "grain_separation")?,
                center_m: to_hpr(num(motor, "grains_center_of_mass_position")?),
                inhibited_ends: motor["only_radial_burn"]
                    .as_bool()
                    .ok_or("only_radial_burn")?,
            }),
            num(motor, "center_of_dry_mass_position")?,
            Some(num(motor, "throat_radius")?),
        ),
        // GenericMotor: a solid cylinder of propellant at the chamber; an unset or zero dry centre
        // falls back to the chamber (rocketpy/motors/motor.py:1518-1523).
        "generic" => {
            let chamber = num(motor, "chamber_position")?;
            (
                Propellant::Column(PropellantColumn {
                    mass_kg: num(motor, "propellant_initial_mass")?,
                    center_m: to_hpr(chamber),
                    outer_radius_m: num(motor, "chamber_radius")?,
                    inner_radius_m: 0.0,
                    length_m: num(motor, "chamber_height")?,
                }),
                match motor["center_of_dry_mass_position"].as_f64() {
                    None | Some(0.0) => chamber,
                    Some(z) => z,
                },
                None,
            )
        }
        other => return Err(format!("unknown motor kind `{other}`")),
    };
    SolidMotor::new(
        thrust,
        propellant,
        MassElement {
            // hpr's motor needs a positive dry mass; RocketPy's Cavour example has none, so it
            // takes 1e-15 kg, below the mass comparison's resolution (1e-12 of the rocket's).
            mass_kg: match num(motor, "dry_mass")? {
                0.0 => 1e-15,
                mass => mass,
            },
            cg_m: to_hpr(dry_cg),
            axial_inertia_kg_m2: dry_33,
            transverse_inertia_kg_m2: dry_11,
        },
        Some(Nozzle {
            exit_radius_m: num(motor, "nozzle_radius")?,
            throat_radius_m: throat,
            reference_pressure_pa: STANDARD_SEA_LEVEL_PRESSURE_PA,
        }),
    )
    .map_err(|e| e.to_string())
}

/// The examples give no case size, so the case is taken as the propellant's envelope: the radius
/// of the grains, chamber or nozzle, whichever is widest, and the length from the nozzle exit to
/// the propellant's forward end.
fn envelope(motor: &Value, solid: &SolidMotor) -> Result<(f64, f64), String> {
    let nozzle = num(motor, "nozzle_radius")?;
    Ok(match solid.propellant() {
        Propellant::Grains(g) => {
            let n = f64::from(g.count);
            let stack = n * g.initial_height_m + (n - 1.0) * g.separation_m;
            (g.outer_radius_m.max(nozzle), g.center_m + 0.5 * stack)
        }
        Propellant::Column(c) => (c.outer_radius_m.max(nozzle), c.center_m + 0.5 * c.length_m),
        _ => return Err("unmapped propellant model".to_owned()),
    })
}

/// A bundled catalog motor, with its catalog envelope, in `mount`.
fn catalog_motor(
    catalog: &Catalog,
    designation: &str,
    mount: &str,
    delay_s: f64,
) -> Result<MountedMotor, String> {
    let entry = catalog
        .motors
        .iter()
        .find(|m| m.designation == designation)
        .ok_or_else(|| format!("no bundled motor {designation}"))?;
    Ok(MountedMotor {
        mount: mount.to_owned(),
        designation: designation.to_owned(),
        diameter_m: entry.diameter_mm * 1e-3,
        length_m: entry.length_mm * 1e-3,
        motor: entry.bundled_motor().map_err(|e| e.to_string())?,
        delay: Some(Delay::Seconds(delay_s)),
    })
}

/// An airframe section: a tube with a motor mount, automatic centering rings, fins and rail
/// buttons.
struct Section<'a> {
    prefix: &'a str,
    tube_length_m: f64,
    tube_radius_m: f64,
    tube_wall_m: f64,
    mount_length_m: f64,
    mount_radius_m: f64,
    root_chord_m: f64,
    tip_chord_m: f64,
    span_m: f64,
    sweep_m: f64,
}

impl Section<'_> {
    fn build(&self) -> Result<Component, String> {
        let p = self.prefix;
        let mut tube = component(
            &format!("{p}-airframe"),
            Part::BodyTube(BodyTube {
                length_m: self.tube_length_m,
                outer_radius_m: self.tube_radius_m,
                thickness_m: self.tube_wall_m,
                material: material("kraft_phenolic")?,
            }),
            None,
        );
        let mut mount = component(
            &format!("{p}-motor-mount"),
            Part::InnerTube(InnerTube {
                length_m: self.mount_length_m,
                outer_radius_m: self.mount_radius_m,
                thickness_m: 0.001,
                radial_offset_m: 0.0,
                angle_rad: 0.0,
                material: material("kraft_phenolic")?,
            }),
            Some(Position::Bottom { aft_offset_m: 0.0 }),
        );
        mount.motor_mount = Some(MotorMount { overhang_m: 0.005 });
        let ring = |id: &str, offset: f64| -> Result<Component, String> {
            let mut ring = component(
                id,
                Part::CenteringRing(CenteringRing {
                    length_m: 0.00635,
                    outer_radius_m: 0.0,
                    inner_radius_m: 0.0,
                    material: material("birch_plywood")?,
                }),
                Some(Position::Bottom {
                    aft_offset_m: offset,
                }),
            );
            ring.auto = vec![AutoDimension::OuterRadius, AutoDimension::InnerRadius];
            Ok(ring)
        };
        let buttons = component(
            &format!("{p}-rail-buttons"),
            Part::RailButton(RailButton {
                outer_diameter_m: 0.0113,
                inner_diameter_m: 0.0064,
                height_m: 0.0081,
                base_height_m: 0.002,
                flange_height_m: 0.002,
                angle_rad: std::f64::consts::FRAC_PI_3,
                count: 2,
                spacing_m: 0.5 * self.tube_length_m,
                material: material("acetal")?,
            }),
            Some(Position::Middle { aft_offset_m: 0.0 }),
        );
        tube.children = vec![
            mount,
            ring(&format!("{p}-ring-forward"), -(self.mount_length_m - 0.02))?,
            ring(&format!("{p}-ring-aft"), -0.005)?,
            component(
                &format!("{p}-fins"),
                Part::FinSet(FinSet {
                    count: 3,
                    planform: FinPlanform::Trapezoidal {
                        root_chord_m: self.root_chord_m,
                        tip_chord_m: self.tip_chord_m,
                        span_m: self.span_m,
                        sweep_m: self.sweep_m,
                    },
                    thickness_m: 0.003175,
                    cross_section: FinCrossSection::Rounded,
                    tab: None,
                    cant_rad: 0.0,
                    base_angle_rad: 0.0,
                    material: material("birch_plywood")?,
                }),
                Some(Position::Bottom {
                    aft_offset_m: -0.005,
                }),
            ),
            buttons,
        ];
        Ok(tube)
    }
}

/// A recovery bay's parachute and shock cord, packed to the tube's bore.
fn recovery(
    prefix: &str,
    chute_diameter_m: f64,
    cord_length_m: f64,
) -> Result<Vec<Component>, String> {
    let packing = |length_m: f64| Packing {
        length_m,
        radius_m: 0.0,
        radial_offset_m: 0.0,
        angle_rad: 0.0,
    };
    let mut chute = component(
        &format!("{prefix}-parachute"),
        Part::Parachute(Parachute {
            diameter_m: chute_diameter_m,
            canopy_material: material("ripstop_nylon")?,
            line_count: 8,
            line_length_m: chute_diameter_m,
            line_material: material("nylon_cord_type_i")?,
            packing: packing(0.12),
        }),
        Some(Position::Top { aft_offset_m: 0.05 }),
    );
    chute.auto = vec![AutoDimension::PackedRadius];
    let mut cord = component(
        &format!("{prefix}-shock-cord"),
        Part::ShockCord(ShockCord {
            length_m: cord_length_m,
            material: material("kevlar_cord_eighth_inch")?,
            packing: packing(0.05),
        }),
        Some(Position::After { aft_offset_m: 0.0 }),
    );
    cord.auto = vec![AutoDimension::PackedRadius];
    Ok(vec![chute, cord])
}

fn ogive_nose(length_m: f64) -> Result<Component, String> {
    let mut nose = component(
        "nose",
        Part::NoseCone(NoseCone {
            shape: NoseShape::Ogive { radius_ratio: 1.0 },
            length_m,
            base_radius_m: 0.0,
            wall: Wall::Shell {
                thickness_m: 0.0015,
            },
            shoulder: Some(Shoulder {
                length_m: 0.06,
                outer_radius_m: 0.0,
                thickness_m: 0.0015,
                capped: true,
            }),
            material: material("abs")?,
        }),
        None,
    );
    nose.auto = vec![AutoDimension::BaseRadius, AutoDimension::ShoulderRadius];
    Ok(nose)
}

/// A 54 mm, single-stage, three-fin rocket on a 38 mm 411I175-14A: mass from geometry.
fn three_fin(catalog: &Catalog) -> Result<Rocket, String> {
    let mut airframe = Section {
        prefix: "sustainer",
        tube_length_m: 0.9,
        tube_radius_m: 0.02815,
        tube_wall_m: 0.00115,
        mount_length_m: 0.3,
        mount_radius_m: 0.02,
        root_chord_m: 0.15,
        tip_chord_m: 0.06,
        span_m: 0.07,
        sweep_m: 0.09,
    }
    .build()?;
    airframe.children.extend(recovery("sustainer", 0.9, 3.0)?);
    airframe.children.push(component(
        "altimeter",
        Part::MassComponent(MassComponent {
            mass_kg: 0.035,
            packing: Packing {
                length_m: 0.06,
                radius_m: 0.012,
                radial_offset_m: 0.0,
                angle_rad: 0.0,
            },
        }),
        Some(Position::Top { aft_offset_m: 0.0 }),
    ));
    Ok(Rocket {
        name: "Synthetic 54 mm three-fin rocket".to_owned(),
        stages: vec![Stage {
            id: "sustainer".to_owned(),
            name: String::new(),
            components: vec![ogive_nose(0.25)?, airframe],
            overrides: Overrides::default(),
        }],
        reference_diameter: ReferenceDiameter::Maximum {},
        configurations: vec![Configuration {
            id: "i175".to_owned(),
            name: String::new(),
            motors: vec![catalog_motor(
                catalog,
                "411I175-14A",
                "sustainer-motor-mount",
                14.0,
            )?],
        }],
    })
}

/// A two-stage rocket: a 54 mm sustainer on a 411I175-14A over a 75 mm booster on a 1266J760-19A,
/// joined by a transition whose radii and forward shoulder are automatic.
fn two_stage(catalog: &Catalog) -> Result<Rocket, String> {
    let mut sustainer = Section {
        prefix: "sustainer",
        tube_length_m: 0.8,
        tube_radius_m: 0.02815,
        tube_wall_m: 0.00115,
        mount_length_m: 0.3,
        mount_radius_m: 0.02,
        root_chord_m: 0.12,
        tip_chord_m: 0.05,
        span_m: 0.06,
        sweep_m: 0.07,
    }
    .build()?;
    sustainer.children.extend(recovery("sustainer", 0.9, 3.0)?);
    let mut interstage = component(
        "interstage",
        Part::Transition(Transition {
            shape: NoseShape::Conical {},
            clipped: false,
            length_m: 0.08,
            fore_radius_m: 0.0,
            aft_radius_m: 0.0,
            wall: Wall::Shell { thickness_m: 0.002 },
            fore_shoulder: Some(Shoulder {
                length_m: 0.05,
                outer_radius_m: 0.0,
                thickness_m: 0.002,
                capped: false,
            }),
            aft_shoulder: None,
            material: material("fiberglass_g10")?,
        }),
        None,
    );
    interstage.auto = vec![
        AutoDimension::ForeRadius,
        AutoDimension::AftRadius,
        AutoDimension::ForeShoulderRadius,
    ];
    let mut booster = Section {
        prefix: "booster",
        tube_length_m: 0.7,
        tube_radius_m: 0.0400,
        tube_wall_m: 0.0015,
        mount_length_m: 0.35,
        mount_radius_m: 0.028,
        root_chord_m: 0.2,
        tip_chord_m: 0.08,
        span_m: 0.1,
        sweep_m: 0.12,
    }
    .build()?;
    booster.children.push(component(
        "booster-electronics",
        Part::MassComponent(MassComponent {
            mass_kg: 0.12,
            packing: Packing {
                length_m: 0.1,
                radius_m: 0.03,
                radial_offset_m: 0.0,
                angle_rad: 0.0,
            },
        }),
        Some(Position::Top { aft_offset_m: 0.05 }),
    ));
    Ok(Rocket {
        name: "Synthetic two-stage rocket, 75 mm booster and 54 mm sustainer".to_owned(),
        stages: vec![
            Stage {
                id: "sustainer".to_owned(),
                name: String::new(),
                components: vec![ogive_nose(0.25)?, sustainer],
                overrides: Overrides::default(),
            },
            Stage {
                id: "booster".to_owned(),
                name: String::new(),
                components: vec![interstage, booster],
                overrides: Overrides::default(),
            },
        ],
        reference_diameter: ReferenceDiameter::Maximum {},
        configurations: vec![Configuration {
            id: "j760-i175".to_owned(),
            name: "every motor ignites at liftoff until staging arrives (M1.9)".to_owned(),
            motors: vec![
                catalog_motor(catalog, "1266J760-19A", "booster-motor-mount", 19.0)?,
                catalog_motor(catalog, "411I175-14A", "sustainer-motor-mount", 14.0)?,
            ],
        }],
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Numbers match to round-off; anything else must be equal.
    #[test]
    fn comparison_allows_round_off_only() {
        let a: Value = serde_json::from_str(r#"{"x": [0.1, 2], "s": "a"}"#).unwrap();
        let close: Value =
            serde_json::from_str(r#"{"x": [0.10000000000000002, 2], "s": "a"}"#).unwrap();
        let far: Value = serde_json::from_str(r#"{"x": [0.1000001, 2], "s": "a"}"#).unwrap();
        let text: Value = serde_json::from_str(r#"{"x": [0.1, 2], "s": "b"}"#).unwrap();
        let longer: Value = serde_json::from_str(r#"{"x": [0.1, 2, 3], "s": "a"}"#).unwrap();
        assert!(same(&a, &close));
        assert!(!same(&a, &far) && !same(&a, &text) && !same(&a, &longer));
    }

    /// The committed designs are what the generator writes from the committed fixture.
    #[test]
    fn committed_designs_match_the_generator() {
        let root = root().unwrap();
        let designs = generate(&root).unwrap();
        assert_eq!(designs.len(), 10);
        let stale = stale(&root.join(DIR), &designs);
        assert!(
            stale.is_empty(),
            "run `cargo xtask designs`; these differ: {stale:?}"
        );
    }
}
